### ISSUE TITLE
How to update job

### ISSUE THREAD

**Issue by supacyan** [ahawker/crython#106]
Not an issue, but a question. Great work btw!

How do I update job with new cron expression.

I tried
crontab.start()
time.sleep(5)
update job expr with 'some new expr'
crontab.stop()
crontab.start()
time.sleep(5)

Not working 
Log:
Traceback (most recent call last):
  File "test-0.py", line 27, in <module>
    crython.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/crython/tab.py", line 129, in start
    default_tab.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 842, in start
    raise RuntimeError("threads can only be started once")
RuntimeError: threads can only be started once

**Comment by ahawker** [comment]
@supacyan 

This use case isn't currently supported. The `CronTab` type does expose a method to `deregister` register jobs so you could use that to remove and then re-add the job instance instead of trying to stop/start the tab instance.
